apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306