apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379