apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP 
    port: 5672
    targetPort: 5672