apiVersion: v1 
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec: 
  selector:
    type: ClusterIP
    project: roboshop
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080